# Arquivo de Configuração para o Script de Automação Gerencie Carteira
# Mantenha este arquivo na mesma pasta que o seu script .py

[Paths]
# Caminho para a pasta onde os anexos HTML dos e-mails serão salvos.
pasta_destino_html = COLE AQUI SEU DIRETÓRIO PARA SALVAR OS HTML

# Caminho para a pasta onde as planilhas diárias do Excel são salvas.
pasta_diario_excel = COLE AQUI SEU DIRETÓRIO PARA SALVAR OS EXCELS DIÁRIOS

# Caminho para a pasta onde a cópia da planilha (em .xlsx, sem macros) será salva.
pasta_copia_excel = COLE AQUI SEU DIRETÓRIO PARA SALVAR AS CÓPIAS DA PASTA COM O EXCEL MAIS RECENTE

# Caminho para o executável que é aberto em caso de erro de gerente.
executavel_direciona = COLE AQUI O CAMINHO PARA O EXECUTÁVEL DO DIRECIONA

# Caminho para a pasta onde os arquivos de log serão salvos.
# Se deixado em branco, o log será salvo na mesma pasta do script.
pasta_logs = COLE AQUI SEU DIRETÓRIO PARA SALVAR OS LOGS

[BaseConsolidada]
# Caminho para a pasta que contém a planilha consolidada.
pasta_base_consolidada = COLE AQUI SEU DIRETÓRIO DA BASE CONSOLIDADA

# Nome EXATO do arquivo Excel (com extensão) que será sempre atualizado.
nome_arquivo_consolidado = COLE AQUI O NOME EXATO DO ARQUIVO DA BASE CONSOLIDADA

[Excel]
# Sheet onde se encontra a base de dados do gerecie carteira
planilha_dados = COLE AQUI O NOME DA SHEET DA BASE DE DADOS DENTRO DO EXCEL

# Coluna de verificação do erro #N/D
coluna_verificacao = LETRA DA COLUNA QUE DEVE SER VERIFICADA PELO ERRO N/D

[Email]
# Assunto exato do e-mail que o script deve procurar.
assunto_procurado = COLE AQUI O ASSUNTO DO EMAIL RECEBIDO PELO SERASA, COSTUMA SER Gerencie Carteira - Consulte as Empresas Monitoradas