# Arquivo de Configuração para o Script de Automação Gerencie Carteira
# Mantenha este arquivo na mesma pasta que o seu script .py

[Paths]
# Caminho para a pasta onde os anexos HTML dos e-mails serão salvos.
pasta_destino_html = C:\Users\comercial05\Documents\Gerencie Carteira\HTML

# Caminho para a pasta onde as planilhas diárias do Excel são salvas.
pasta_diario_excel = C:\Users\comercial05\Documents\Gerencie Carteira\Diário

# Caminho para a pasta onde a cópia da planilha (em .xlsx, sem macros) será salva.
pasta_copia_excel = A:\PUBLICA\GERENCIE CARTEIRA PÚBLICA

# Caminho para o executável que é aberto em caso de erro de gerente.
executavel_direciona = C:\DIRECIONA\atualiza.exe

# Caminho para a pasta onde os arquivos de log serão salvos.
# Se deixado em branco, o log será salvo na mesma pasta do script.
pasta_logs = C:\Users\comercial05\Desktop\PROGRAMAS PYTHON\Gerencie Carteira\versions\main\2.13.0\log

[BaseConsolidada]
# Caminho para a pasta que contém a planilha consolidada.
pasta_base_consolidada = A:\COMERCIAL\Gerencie Carteira Comercial

# Nome EXATO do arquivo Excel (com extensão) que será sempre atualizado.
nome_arquivo_consolidado = Gerencie Carteira Base Atualizada.xlsm

[Excel]
# Sheet onde se encontra a base de dados do gerecie carteira
planilha_dados = E-Mail BD

# Coluna de verificação do erro #N/D
coluna_verificacao = E

[Email]
# Assunto exato do e-mail que o script deve procurar.
assunto_procurado = Gerencie Carteira - Consulte as Empresas Monitoradas