# Arquivo de Configuração para o Script de Automação Gerencie Carteira
# Mantenha este arquivo na mesma pasta que o seu script .py

[Paths]
# Caminho para a pasta onde os anexos HTML dos e-mails serão salvos.
pasta_destino_html = C:\Users\comercial05\Documents\Gerencie Carteira\HTML

# Caminho para a pasta onde as planilhas diárias do Excel são salvas.
pasta_diario_excel = C:\Users\comercial05\Documents\Gerencie Carteira\Diário

# Caminho para o executável que é aberto em caso de erro de gerente.
executavel_direciona = C:\DIRECIONA\atualiza.exe

[Email]
# Assunto exato do e-mail que o script deve procurar.
assunto_procurado = Gerencie Carteira - Consulte as Empresas Monitoradas